In [2]:
# Import the required libraries and dependencies
import pandas as pd
import datetime as dt
from prophet import Prophet
import pandas as pd
import datetime as dt
from prophet import Prophet
import yfinance as yf
import matplotlib.pyplot as plt
import numpy as np
from scipy.signal import correlate
from datetime import date

In [ ]:
#read economic data file
economic_data = pd.read_csv("./Resources/economic_data.csv", index_col="Date", parse_dates=True)

#clear any null values
economic_data = economic_data.dropna()

#set date to datetime
economic_data.index = pd.to_datetime(economic_data.index)

economic_data.head()

,SNP_Close,10YTrate,GoldPrice,FedRate,Unemployment Rate,InflationRate
Date,,,,,,
2007-02-01,1444.794737,4.721789,657.400024,5.26,4.5,2.4
2007-03-01,1406.952273,4.559091,662.299988,5.26,4.4,2.8
2007-05-01,1511.136818,4.744273,674.400024,5.25,4.4,2.7
2007-06-01,1514.489524,5.098714,671.200012,5.25,4.6,2.7
2007-08-01,1454.616957,4.670174,663.599976,5.02,4.6,2.0

In [14]:
#prep economic data for prophet
economic_data_p = economic_data.reset_index()

#creates dataframes for each economic indicator
unemployment = economic_data_p[["Date", "Unemployment Rate"]]
inflation = economic_data_p[["Date", "InflationRate"]]
SNP_Close = economic_data_p[["Date", "SNP_Close"]]
Trate = economic_data_p[["Date", "10YTrate"]]
GoldPrice = economic_data_p[["Date", "GoldPrice"]]